#!/usr/bin/env bash
# CronCompose interactive setup for local development.
#
# Walks through PostgreSQL (local or remote, new or existing database), ports,
# admin account, secrets, migrations, and writes a dev .env you can source before
# starting the control plane and web UI.
#
# Usage:
#   ./setup.sh
#   ./setup.sh --non-interactive   # use CC_* env vars / defaults
#
# Does not start services; after it finishes, run the printed commands (or make dev).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$SCRIPT_DIR"
LIB_DIR="$REPO_ROOT/install/lib"
NONINTERACTIVE=0

usage() {
  cat <<'EOF'
CronCompose setup (development)

Interactive configuration: PostgreSQL, ports, admin login, secrets, migrations, .env.

Options:
  --non-interactive   accept CC_* env vars and defaults without prompting
  -h, --help          show this help

After setup:
  source .env   # or: set -a; source .env; set +a
  make control-plane && ./control-plane/bin/control-plane
  make web        # in another terminal
EOF
  exit 0
}

while [ $# -gt 0 ]; do
  case "$1" in
    --non-interactive) NONINTERACTIVE=1 ;;
    -h|--help) usage ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done
export NONINTERACTIVE

# shellcheck source=install/lib/common.sh
. "$LIB_DIR/common.sh"
# shellcheck source=install/lib/preflight.sh
. "$LIB_DIR/preflight.sh"
# shellcheck source=install/lib/pgdetect.sh
. "$LIB_DIR/pgdetect.sh"
# shellcheck source=install/lib/setup_db.sh
. "$LIB_DIR/setup_db.sh"
# shellcheck source=install/lib/database.sh
. "$LIB_DIR/database.sh"

banner() {
  printf '%s\n' "$C_CYAN$C_BOLD" >&2
  cat >&2 <<'ART'
   ___                 ___
  / __|_ _ ___ _ _    / __|___ _ __  _ __  ___ ___ ___
 | (__| '_/ _ \ ' \  | (__/ _ \ '  \| '_ \/ _ (_-</ -_)
  \___|_| \___/_||_|  \___\___/_|_|_| .__/\___/__/\___|
                                    |_|   setup
ART
  printf '%s' "$C_RESET" >&2
  dim "Configures PostgreSQL, writes .env, applies migrations, builds binaries."
  dim "For a full production install with pm2, use ./install/install.sh instead."
}

setup_admin() {
  step "Administrator account"
  dim "This is the login for the web UI (seeded on every control-plane boot)."
  ADMIN_EMAIL="$(prompt "Admin email" "${CC_ADMIN_EMAIL:-admin@localhost}")"
  ADMIN_PASSWORD="$(prompt_secret "Admin password (blank = generate)" "${CC_ADMIN_PASSWORD:-}")"
  if [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD="$(gen_hex 12)"
    ADMIN_PASSWORD_GENERATED=1
    ok "generated admin password: $ADMIN_PASSWORD"
  fi
}

setup_ports() {
  step "Ports"
  dim "Backend is the control plane HTTP port. Frontend is the Next.js UI."
  dim "Agent gRPC is where enrolled agents connect (needed even for a remote agent)."
  local taken=""
  API_PORT="$(prompt_port "Backend HTTP port" "${CC_API_PORT:-8080}" "$taken")"
  taken="$API_PORT"
  WEB_PORT="$(prompt_port "Frontend port (web UI)" "${CC_WEB_PORT:-3000}" "$taken")"
  taken="$taken $WEB_PORT"
  GRPC_PORT="$(prompt_port "Agent gRPC port" "${CC_GRPC_PORT:-9090}" "$taken")"
  ok "backend=$API_PORT  frontend=$WEB_PORT  agent=$GRPC_PORT"
}

setup_secrets() {
  step "Secrets"
  SESSION_SECRET="$(gen_hex 32)"
  SECRETS_MASTER_KEY="$(gen_hex 32)"
  if [ -f "$REPO_ROOT/.env" ]; then
    local prev_session prev_master
    prev_session="$(env_unquote "$(sed -n 's/^SESSION_SECRET=//p' "$REPO_ROOT/.env" | head -1)")"
    prev_master="$(env_unquote "$(sed -n 's/^SECRETS_MASTER_KEY=//p' "$REPO_ROOT/.env" | head -1)")"
    [ -n "$prev_session" ] && SESSION_SECRET="$prev_session"
    [ -n "$prev_master" ]  && SECRETS_MASTER_KEY="$prev_master"
    [ -n "$prev_master" ] && ok "reusing secrets from the existing .env"
  fi
  TLS_DIR="${CC_TLS_DIR:-./tls}"
  ok "session and encryption keys ready"
}

write_dev_env() {
  step "Writing .env"
  ENV_FILE="$REPO_ROOT/.env"
  umask 077
  {
    echo "# Generated by setup.sh on $(date). Development configuration."
    env_line APP_ENV dev
    env_line LOG_LEVEL "${CC_LOG_LEVEL:-info}"
    env_line DATABASE_URL "$DATABASE_URL"
    env_line DB_BOOTSTRAP none
    env_line AUTO_BOOTSTRAP_DB 0
    env_line HTTP_ADDR ":${API_PORT}"
    env_line GRPC_ADDR ":${GRPC_PORT}"
    env_line TLS_DIR "$TLS_DIR"
    env_line TLS_HOSTS "localhost,127.0.0.1"
    env_line SESSION_SECRET "$SESSION_SECRET"
    env_line SECRETS_MASTER_KEY "$SECRETS_MASTER_KEY"
    env_line SEED_ADMIN_EMAIL "$ADMIN_EMAIL"
    env_line SEED_ADMIN_PASSWORD "$ADMIN_PASSWORD"
    env_line PUBLIC_HTTP_URL "http://localhost:${API_PORT}/api/v1"
    env_line PUBLIC_GRPC_ADDR "localhost:${GRPC_PORT}"
    env_line PORT "$WEB_PORT"
    env_line API_BASE "http://127.0.0.1:${API_PORT}/api/v1"
    env_line CC_API_PORT "$API_PORT"
    env_line CC_GRPC_PORT "$GRPC_PORT"
    env_line CC_WEB_PORT "$WEB_PORT"
    env_line CC_DB_METHOD "${DB_METHOD:-existing}"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  ok "wrote $ENV_FILE (mode 600)"
}

build_tools() {
  step "Building tools"
  export GOTOOLCHAIN=local
  ( cd "$REPO_ROOT/control-plane" && go build -o bin/migrate ./cmd/migrate ) || die "migrate build failed"
  ok "migrate"
  ( cd "$REPO_ROOT/control-plane" && go build -o bin/control-plane ./cmd/server ) || die "control-plane build failed"
  ok "control-plane"
  ( cd "$REPO_ROOT/agent" && go build -o bin/agent ./cmd/agent ) || die "agent build failed"
  ok "agent"
}

provision_setup_database() {
  step "Preparing database"
  case "${DB_METHOD:-existing}" in
    psql)
      provision_db_psql || die "could not create the local database"
      ;;
    remote_create)
      provision_remote_create || die "could not create the remote database"
      DB_METHOD="existing"
      ;;
    existing)
      ok "using the database you selected (no provisioning step)"
      ;;
    *)
      ok "database method: ${DB_METHOD:-existing}"
      ;;
  esac
}

apply_setup_migrations() {
  step "Applying migrations"
  local migrate_bin="$REPO_ROOT/control-plane/bin/migrate"
  [ -x "$migrate_bin" ] || die "migrate tool missing at $migrate_bin"
  DATABASE_URL="$DATABASE_URL" "$migrate_bin" -dir "$REPO_ROOT/migrations" \
    || die "migrations failed — check DATABASE_URL and role permissions"
  ok "schema is up to date"
}

seed_admin() {
  step "Seeding administrator"
  local bin="$REPO_ROOT/control-plane/bin/control-plane"
  [ -x "$bin" ] || die "control-plane binary missing at $bin"
  # Loads .env from the repo root (no need to source it). Inserts the admin so
  # login works even if a leftover control-plane process was started without .env.
  ( cd "$REPO_ROOT" && "$bin" -seed-and-exit ) \
    || die "could not seed admin — is Postgres reachable with DATABASE_URL?"
  ok "admin $ADMIN_EMAIL is ready to sign in"
}

print_summary() {
  step "Done"
  ok "CronCompose is configured for local development"
  echo >&2
  info "Sign in with:"
  info "  email:    $ADMIN_EMAIL"
  if [ "${ADMIN_PASSWORD_GENERATED:-0}" = "1" ]; then
    info "  password: $ADMIN_PASSWORD  ${C_DIM}(generated — save this)${C_RESET}"
  else
    info "  password: (the one you entered)"
  fi
  echo >&2
  info "Start the stack:"
  info "  ./control-plane/bin/control-plane          # REST :${API_PORT}, gRPC :${GRPC_PORT} (reads .env)"
  info "  cd web && npm install && npm run dev       # UI http://localhost:${WEB_PORT}/app"
  echo >&2
  info "Enroll an agent (optional):"
  info "  cd agent && go run ./cmd/agent enroll --token=<from UI>"
  info "  cd agent && go run ./cmd/agent run"
  echo >&2
  dim "Production install with pm2: ./install/install.sh"
}

main() {
  banner
  step "Checking prerequisites"
  detect_platform
  check_go
  detect_db_tools

  setup_database
  setup_admin
  setup_ports
  setup_secrets
  write_dev_env
  build_tools
  provision_setup_database
  apply_setup_migrations
  seed_admin
  print_summary
}

main "$@"
