#!/usr/bin/env bash
# PM2 is the process manager for the whole stack. ecosystem.config.js at the repo
# root is the single source of truth for what runs; this file only makes sure pm2
# exists, drives it during install, and writes croncompose-ctl.sh as a thin wrapper
# so the commands printed in the summary keep working.

PM2_BIN=""

# Resolve (or install) pm2. Prefers an existing binary, then a global npm install,
# then npx as a last resort so a locked-down box can still finish the install.
ensure_pm2() {
  step "Checking for pm2"
  if command -v pm2 >/dev/null 2>&1; then
    PM2_BIN="$(command -v pm2)"
    ok "pm2 found ($("$PM2_BIN" -v 2>/dev/null || echo unknown))"
    return 0
  fi
  command -v npm >/dev/null 2>&1 || die "pm2 is required and npm is not installed; install Node.js first"

  info "pm2 not found; installing it globally with npm"
  if npm install -g pm2 >/dev/null 2>&1 && command -v pm2 >/dev/null 2>&1; then
    PM2_BIN="$(command -v pm2)"
    ok "installed pm2"
    return 0
  fi
  warn "global install failed (try: sudo npm install -g pm2); falling back to npx"
  command -v npx >/dev/null 2>&1 || die "could not obtain pm2"
  PM2_BIN="npx --yes pm2"
}

# Run pm2 from the repo root so relative paths in ecosystem.config.js resolve.
pm2_run() { ( cd "$REPO_ROOT" && $PM2_BIN "$@" ); }

write_ctl_script() {
  step "Generating control script"
  CTL="$REPO_ROOT/croncompose-ctl.sh"
  cat > "$CTL" <<'CTL_EOF'
#!/usr/bin/env bash
# CronCompose control script (generated by install.sh).
# A thin wrapper over pm2 + ecosystem.config.js, which holds the real process
# definitions. Anything pm2 can do is still available directly: `pm2 status`,
# `pm2 monit`, `pm2 logs croncompose-web`, and so on.
#
# Usage: ./croncompose-ctl.sh {start|stop|restart|reload|status|logs [service]|save|boot|delete}
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
[ -f "$HERE/.env" ] || { echo "missing .env beside croncompose-ctl.sh; run ./install/install.sh" >&2; exit 1; }
[ -f "$HERE/ecosystem.config.js" ] || { echo "missing ecosystem.config.js at $HERE" >&2; exit 1; }

if command -v pm2 >/dev/null 2>&1; then PM2="pm2"; else PM2="npx --yes pm2"; fi
ECO="$HERE/ecosystem.config.js"

# --update-env makes pm2 re-read .env through ecosystem.config.js; without it a
# restart would silently keep the values from the last start.
case "${1:-}" in
  start)   cd "$HERE" && $PM2 start   "$ECO" --update-env ;;
  stop)    cd "$HERE" && $PM2 stop    "$ECO" ;;
  restart) cd "$HERE" && $PM2 restart "$ECO" --update-env ;;
  reload)  cd "$HERE" && $PM2 reload  "$ECO" --update-env ;;
  delete)  cd "$HERE" && $PM2 delete  "$ECO" ;;
  status)  cd "$HERE" && $PM2 status ;;
  logs)    svc="${2:-}"; cd "$HERE" && { [ -n "$svc" ] && $PM2 logs "croncompose-$svc" --lines 100 || $PM2 logs --lines 100; } ;;
  save)    cd "$HERE" && $PM2 save ;;
  boot)    cd "$HERE" && $PM2 startup && $PM2 save ;;   # prints a sudo line to run once
  *) echo "usage: $0 {start|stop|restart|reload|status|logs [control-plane|web|agent]|save|boot|delete}"; exit 1 ;;
esac
CTL_EOF
  chmod +x "$CTL"
  ok "wrote $CTL (pm2 wrapper)"
}

# Bring the stack up under pm2 and persist the process list so it survives a reboot
# once the user has run `pm2 startup`.
start_stack() {
  step "Starting services under pm2"
  mkdir -p "$RUNTIME_DIR/logs" "$RUNTIME_DIR/run" "$RUNTIME_DIR/tls" "$RUNTIME_DIR/agent"
  pm2_run start "$REPO_ROOT/ecosystem.config.js" --update-env >&2 || die "pm2 could not start the stack (see: pm2 logs)"
  pm2_run save >/dev/null 2>&1 || warn "pm2 save failed; the stack will not come back after a reboot"
  wait_for_health || warn "control plane health check timed out (see: ./croncompose-ctl.sh logs control-plane)"
}

wait_for_health() {
  local i=0
  while [ "$i" -lt 60 ]; do
    curl -fsS -o /dev/null "http://127.0.0.1:$API_PORT/healthz" 2>/dev/null && { ok "control plane healthy on :$API_PORT"; return 0; }
    i=$((i + 1)); sleep 0.5
  done
  return 1
}

# The agent process only appears in ecosystem.config.js once an identity exists, so
# re-run pm2 start after enrollment to pick it up.
restart_stack() { pm2_run start "$REPO_ROOT/ecosystem.config.js" --update-env >/dev/null 2>&1 || true; }

# Stop a previous install's processes before probing for free ports. pm2 owns them
# now; the pidfile-based script from older installs is handled too.
stop_existing_stack() {
  if [ -f "$REPO_ROOT/ecosystem.config.js" ] && command -v pm2 >/dev/null 2>&1; then
    step "Stopping any previously-installed stack"
    ( cd "$REPO_ROOT" && pm2 delete ecosystem.config.js >/dev/null 2>&1 ) || true
  fi
  # Legacy: a croncompose-ctl.sh from before the pm2 refactor managed its own pids.
  if [ -x "$REPO_ROOT/croncompose-ctl.sh" ] && grep -q 'nohup' "$REPO_ROOT/croncompose-ctl.sh" 2>/dev/null; then
    "$REPO_ROOT/croncompose-ctl.sh" stop >/dev/null 2>&1 || true
  fi
}
