#!/usr/bin/env bash
# Service lifecycle: generate the standalone control script, bring the stack up, and
# enroll + start a local agent. The generated croncompose-ctl.sh owns start/stop logic
# so there is a single source of truth the user keeps using after install.

# Extract a JSON string value without depending on jq.
json_string() { # <json> <key>
  printf '%s' "$1" | tr -d '\n' | grep -o "\"$2\":\"[^\"]*\"" | head -1 | sed "s/^\"$2\":\"//; s/\"$//"
}

write_ctl_script() {
  step "Generating control script"
  CTL="$REPO_ROOT/croncompose-ctl.sh"
  cat > "$CTL" <<'CTL_EOF'
#!/usr/bin/env bash
# CronCompose process manager (generated by install.sh).
# Usage: ./croncompose-ctl.sh {start|stop|restart|status|logs [service]}
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$HERE/.env"
[ -f "$ENV_FILE" ] || { echo "missing .env beside croncompose-ctl.sh" >&2; exit 1; }

# Load .env (first '=' splits key/value; values kept verbatim).
while IFS= read -r line; do
  case "$line" in ''|\#*) continue ;; esac
  key="${line%%=*}"; val="${line#*=}"
  [ -n "$key" ] && export "$key=$val"
done < "$ENV_FILE"

RUNTIME_DIR="${CC_RUNTIME_DIR:-$HERE/.run}"
LOGS="$RUNTIME_DIR/logs"; RUNDIR="$RUNTIME_DIR/run"
mkdir -p "$LOGS" "$RUNDIR" "$RUNTIME_DIR/tls" "$RUNTIME_DIR/agent"
CP_BIN="$HERE/control-plane/bin/control-plane"
AGENT_BIN="$HERE/agent/bin/agent"
API_PORT="${CC_API_PORT:-8080}"; WEB_PORT="${CC_WEB_PORT:-3000}"

alive()  { [ -f "$1" ] && kill -0 "$(cat "$1" 2>/dev/null)" 2>/dev/null; }
listen() { # port -> 0 if bound
  if command -v lsof >/dev/null 2>&1; then lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1; return; fi
  ( exec 3<>"/dev/tcp/127.0.0.1/$1" ) >/dev/null 2>&1 && { exec 3>&- 3<&- 2>/dev/null; return 0; }; return 1
}
wait_http(){ i=0; while [ "$i" -lt 60 ]; do curl -fsS -o /dev/null "$1" 2>/dev/null && return 0; i=$((i+1)); sleep 0.5; done; return 1; }
wait_listen(){ i=0; while [ "$i" -lt 60 ]; do listen "$1" && return 0; i=$((i+1)); sleep 0.5; done; return 1; }

start_proc(){ # name pidfile cmd...
  name="$1"; pf="$2"; shift 2
  if alive "$pf"; then echo "  $name already running (pid $(cat "$pf"))"; return 0; fi
  # Detach fully (stdin from /dev/null, stdout+stderr to the log) so the daemon never
  # holds a caller's pipe or terminal open.
  ( cd "$HERE" && nohup "$@" >"$LOGS/$name.log" 2>&1 </dev/null & echo $! >"$pf" )
  echo "  started $name (pid $(cat "$pf"))"
}

do_start(){
  echo "Starting CronCompose..."
  start_proc control-plane "$RUNDIR/control-plane.pid" "$CP_BIN"
  wait_http "http://127.0.0.1:$API_PORT/healthz" && echo "  control-plane healthy on :$API_PORT" || echo "  ! control-plane health check timed out (see $LOGS/control-plane.log)"
  if [ "${CC_ENABLE_WEB:-1}" = "1" ]; then
    web_pf="$RUNDIR/web.pid"; std="$HERE/web/.next/standalone"
    # The control plane reverse-proxies /app to the UI, so the UI only needs loopback.
    if alive "$web_pf"; then echo "  web already running (pid $(cat "$web_pf"))"
    elif [ -f "$std/server.js" ]; then
      # Next.js standalone server: cwd must be the standalone dir; reads PORT/HOSTNAME.
      ( cd "$std" && PORT="$WEB_PORT" HOSTNAME="127.0.0.1" API_BASE="${API_BASE:-}" \
          nohup node server.js >"$LOGS/web.log" 2>&1 </dev/null & echo $! >"$web_pf" )
      echo "  started web (pid $(cat "$web_pf"))"
      wait_listen "$WEB_PORT" && echo "  web listening on :$WEB_PORT (internal)" || echo "  ! web did not bind :$WEB_PORT (see $LOGS/web.log)"
    else
      echo "  ! web build missing ($std/server.js); re-run the installer with web enabled"
    fi
  fi
  if [ "${CC_ENABLE_AGENT:-0}" = "1" ] && [ -f "$RUNTIME_DIR/agent/identity.json" ]; then
    start_proc agent "$RUNDIR/agent.pid" "$AGENT_BIN" run
  fi
}

stop_one(){ name="$1"; pf="$RUNDIR/$name.pid"; if alive "$pf"; then kill "$(cat "$pf")" 2>/dev/null && echo "  stopped $name"; rm -f "$pf"; else echo "  $name not running"; fi; }
do_stop(){ echo "Stopping CronCompose..."; stop_one agent; stop_one web; stop_one control-plane; }

do_status(){
  for s in control-plane web agent; do
    pf="$RUNDIR/$s.pid"
    if alive "$pf"; then echo "  $s: running (pid $(cat "$pf"))"; else echo "  $s: stopped"; fi
  done
  listen "$API_PORT" && echo "  http :$API_PORT bound (public)" || echo "  http :$API_PORT free"
  listen "$WEB_PORT" && echo "  web  :$WEB_PORT bound (internal)" || echo "  web  :$WEB_PORT free"
}

case "${1:-}" in
  start)   do_start ;;
  stop)    do_stop ;;
  restart) do_stop; sleep 1; do_start ;;
  status)  do_status ;;
  logs)    svc="${2:-control-plane}"; tail -n 100 -f "$LOGS/$svc.log" ;;
  *) echo "usage: $0 {start|stop|restart|status|logs [control-plane|web|agent]}"; exit 1 ;;
esac
CTL_EOF
  chmod +x "$CTL"
  ok "wrote $CTL"
}

start_stack() {
  step "Starting services"
  mkdir -p "$RUNTIME_DIR/logs" "$RUNTIME_DIR/run" "$RUNTIME_DIR/tls" "$RUNTIME_DIR/agent"
  # Do not pipe: croncompose-ctl.sh launches long-lived daemons, and a read-pipe would
  # never see EOF (the daemon keeps the write end open), hanging the installer.
  "$CTL" start >&2
}

enroll_local_agent() {
  [ "${ENABLE_AGENT:-0}" = "1" ] || return 0
  step "Enrolling local agent"
  local api="http://127.0.0.1:$API_PORT/api/v1"
  local cookie="$RUNTIME_DIR/run/cc-cookies.txt"
  local hostname_label; hostname_label="local-$(hostname 2>/dev/null || echo host)"

  if [ -f "$RUNTIME_DIR/agent/identity.json" ]; then ok "agent already enrolled"; "$CTL" start >/dev/null 2>&1 || true; return 0; fi

  curl -fsS -c "$cookie" -X POST "$api/auth/login" -H 'content-type: application/json' \
    -d "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\"}" >/dev/null 2>&1 \
    || { warn "could not log in to mint an enrollment token; skipping agent. Enroll later from the UI."; return 0; }

  local resp token
  resp="$(curl -fsS -b "$cookie" -X POST "$api/servers" -H 'content-type: application/json' \
    -d "{\"name\":\"$hostname_label\",\"description\":\"local agent (installer)\"}" 2>/dev/null || true)"
  token="$(json_string "$resp" token)"
  [ -n "$token" ] || { warn "no enrollment token returned; skipping agent."; return 0; }

  DATA_DIR="$RUNTIME_DIR/agent" \
  CONTROL_PLANE_HTTP="$api" \
  CONTROL_PLANE_ADDR="127.0.0.1:$GRPC_PORT" \
  CONTROL_PLANE_SNI="$AGENT_SNI" \
    "$REPO_ROOT/agent/bin/agent" enroll --token="$token" >/dev/null 2>&1 \
    && ok "agent enrolled" || { warn "agent enrollment failed; the stack is up without a local agent."; return 0; }

  "$CTL" start >/dev/null 2>&1 || true
  # Best-effort online confirmation.
  local i=0
  while [ "$i" -lt 15 ]; do
    curl -fsS -b "$cookie" "$api/servers" 2>/dev/null | grep -q '"status":"online"' && { ok "agent is online"; return 0; }
    i=$((i + 1)); sleep 0.5
  done
  warn "agent enrolled but not yet reporting online (check: ./croncompose-ctl.sh logs agent)"
}

print_summary() {
  # The control plane's HTTP port fronts the UI (/app) and REST (/api); agents use
  # the gRPC port directly.
  local ui_url="http://$ADVERTISE_HOST:$API_PORT/app"
  local rest_url="http://$ADVERTISE_HOST:$API_PORT/api/v1"
  local grpc_addr="$ADVERTISE_HOST:$GRPC_PORT"
  printf '\n%s%s CronCompose is installed and running %s\n' "$C_GREEN" "============" "$C_RESET" >&2
  info ""
  info "Web UI:        $ui_url"
  dim "(the bare host:port redirects to /app)"
  info "REST API:      $rest_url   (health: /healthz)"
  info "Agent gRPC:    $grpc_addr"
  info ""
  info "Sign in with:  $ADMIN_EMAIL"
  if [ "${ADMIN_PASSWORD_GENERATED:-0}" = "1" ]; then
    info "Password:      $ADMIN_PASSWORD   (generated; save it now)"
  else
    info "Password:      (the one you entered)"
  fi
  info ""
  info "Manage the stack with the generated control script:"
  info "  ./croncompose-ctl.sh status     # what's running"
  info "  ./croncompose-ctl.sh logs web    # tail a log"
  info "  ./croncompose-ctl.sh restart     # restart everything"
  info "  ./croncompose-ctl.sh stop        # stop everything"
  info ""
  info "Config + secrets live in .env (mode 600). Runtime state in: $RUNTIME_DIR"
  if [ "${ENABLE_AGENT:-0}" = "1" ]; then
    info "A local agent is enrolled and running on this machine."
  fi
  dim "For production, set Advertise host to a real DNS name, front the API/UI with TLS,"
  dim "and replace the self-signed CA under $RUNTIME_DIR/tls with your own PKI."
}

# Best-effort: stop a stack left running by a previous install BEFORE we probe for free
# ports, so its daemons don't (a) get orphaned when new pidfiles overwrite the old ones,
# or (b) push port auto-selection onto higher, colliding numbers. Safe on a first install
# (no control script yet).
stop_existing_stack() {
  [ -x "$REPO_ROOT/croncompose-ctl.sh" ] || return 0
  step "Stopping any previously-installed stack"
  "$REPO_ROOT/croncompose-ctl.sh" stop >&2 2>/dev/null || true
}

run_services() {
  write_ctl_script
  start_stack
  enroll_local_agent
  print_summary
}
