// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // one-time enrollment token from the UI
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	CsrPem        []byte                 `protobuf:"bytes,5,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"` // PEM-encoded certificate signing request from the agent
	AgentVersion  string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EnrollRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type EnrollResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServerId             string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ClientCertPem        []byte                 `protobuf:"bytes,2,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"` // signed client certificate (production path)
	ServerCaPem          []byte                 `protobuf:"bytes,3,opt,name=server_ca_pem,json=serverCaPem,proto3" json:"server_ca_pem,omitempty"`       // CA cert the agent should pin (production path)
	ControlPlaneGrpcAddr string                 `protobuf:"bytes,4,opt,name=control_plane_grpc_addr,json=controlPlaneGrpcAddr,proto3" json:"control_plane_grpc_addr,omitempty"`
	// MVP simplification: bearer token the agent presents as the "x-agent-token"
	// metadata header on AgentStream. Production swaps this for mTLS using the cert/ca
	// fields above. See docs/security.md.
	AgentToken    string `protobuf:"bytes,5,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *EnrollResponse) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

func (x *EnrollResponse) GetServerCaPem() []byte {
	if x != nil {
		return x.ServerCaPem
	}
	return nil
}

func (x *EnrollResponse) GetControlPlaneGrpcAddr() string {
	if x != nil {
		return x.ControlPlaneGrpcAddr
	}
	return ""
}

func (x *EnrollResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ConfigAck
	//	*AgentMessage_RunStarted
	//	*AgentMessage_LogChunk
	//	*AgentMessage_RunFinished
	//	*AgentMessage_ConnectorEvent
	//	*AgentMessage_ConnectorResult
	//	*AgentMessage_TerminalOutput
	Body          isAgentMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetBody() isAgentMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetConfigAck() *ConfigAck {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ConfigAck); ok {
			return x.ConfigAck
		}
	}
	return nil
}

func (x *AgentMessage) GetRunStarted() *RunStarted {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_RunStarted); ok {
			return x.RunStarted
		}
	}
	return nil
}

func (x *AgentMessage) GetLogChunk() *LogChunk {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_LogChunk); ok {
			return x.LogChunk
		}
	}
	return nil
}

func (x *AgentMessage) GetRunFinished() *RunFinished {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_RunFinished); ok {
			return x.RunFinished
		}
	}
	return nil
}

func (x *AgentMessage) GetConnectorEvent() *ConnectorEvent {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ConnectorEvent); ok {
			return x.ConnectorEvent
		}
	}
	return nil
}

func (x *AgentMessage) GetConnectorResult() *ConnectorResult {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ConnectorResult); ok {
			return x.ConnectorResult
		}
	}
	return nil
}

func (x *AgentMessage) GetTerminalOutput() *TerminalOutput {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_TerminalOutput); ok {
			return x.TerminalOutput
		}
	}
	return nil
}

type isAgentMessage_Body interface {
	isAgentMessage_Body()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ConfigAck struct {
	ConfigAck *ConfigAck `protobuf:"bytes,3,opt,name=config_ack,json=configAck,proto3,oneof"`
}

type AgentMessage_RunStarted struct {
	RunStarted *RunStarted `protobuf:"bytes,4,opt,name=run_started,json=runStarted,proto3,oneof"`
}

type AgentMessage_LogChunk struct {
	LogChunk *LogChunk `protobuf:"bytes,5,opt,name=log_chunk,json=logChunk,proto3,oneof"`
}

type AgentMessage_RunFinished struct {
	RunFinished *RunFinished `protobuf:"bytes,6,opt,name=run_finished,json=runFinished,proto3,oneof"`
}

type AgentMessage_ConnectorEvent struct {
	ConnectorEvent *ConnectorEvent `protobuf:"bytes,7,opt,name=connector_event,json=connectorEvent,proto3,oneof"` // unsolicited connector discovery push
}

type AgentMessage_ConnectorResult struct {
	ConnectorResult *ConnectorResult `protobuf:"bytes,8,opt,name=connector_result,json=connectorResult,proto3,oneof"` // reply to a ConnectorCommand
}

type AgentMessage_TerminalOutput struct {
	TerminalOutput *TerminalOutput `protobuf:"bytes,9,opt,name=terminal_output,json=terminalOutput,proto3,oneof"` // web terminal: pty / command output
}

func (*AgentMessage_Hello) isAgentMessage_Body() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Body() {}

func (*AgentMessage_ConfigAck) isAgentMessage_Body() {}

func (*AgentMessage_RunStarted) isAgentMessage_Body() {}

func (*AgentMessage_LogChunk) isAgentMessage_Body() {}

func (*AgentMessage_RunFinished) isAgentMessage_Body() {}

func (*AgentMessage_ConnectorEvent) isAgentMessage_Body() {}

func (*AgentMessage_ConnectorResult) isAgentMessage_Body() {}

func (*AgentMessage_TerminalOutput) isAgentMessage_Body() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerMessage_SyncJobs
	//	*ServerMessage_RunNow
	//	*ServerMessage_CancelRun
	//	*ServerMessage_UpdateAgent
	//	*ServerMessage_ConnectorCommand
	//	*ServerMessage_TerminalInput
	Body          isServerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMessage) GetBody() isServerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetSyncJobs() *SyncJobs {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_SyncJobs); ok {
			return x.SyncJobs
		}
	}
	return nil
}

func (x *ServerMessage) GetRunNow() *RunNow {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_RunNow); ok {
			return x.RunNow
		}
	}
	return nil
}

func (x *ServerMessage) GetCancelRun() *CancelRun {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_CancelRun); ok {
			return x.CancelRun
		}
	}
	return nil
}

func (x *ServerMessage) GetUpdateAgent() *UpdateAgent {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_UpdateAgent); ok {
			return x.UpdateAgent
		}
	}
	return nil
}

func (x *ServerMessage) GetConnectorCommand() *ConnectorCommand {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_ConnectorCommand); ok {
			return x.ConnectorCommand
		}
	}
	return nil
}

func (x *ServerMessage) GetTerminalInput() *TerminalInput {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_TerminalInput); ok {
			return x.TerminalInput
		}
	}
	return nil
}

type isServerMessage_Body interface {
	isServerMessage_Body()
}

type ServerMessage_SyncJobs struct {
	SyncJobs *SyncJobs `protobuf:"bytes,1,opt,name=sync_jobs,json=syncJobs,proto3,oneof"`
}

type ServerMessage_RunNow struct {
	RunNow *RunNow `protobuf:"bytes,2,opt,name=run_now,json=runNow,proto3,oneof"`
}

type ServerMessage_CancelRun struct {
	CancelRun *CancelRun `protobuf:"bytes,3,opt,name=cancel_run,json=cancelRun,proto3,oneof"`
}

type ServerMessage_UpdateAgent struct {
	UpdateAgent *UpdateAgent `protobuf:"bytes,4,opt,name=update_agent,json=updateAgent,proto3,oneof"`
}

type ServerMessage_ConnectorCommand struct {
	ConnectorCommand *ConnectorCommand `protobuf:"bytes,5,opt,name=connector_command,json=connectorCommand,proto3,oneof"` // targeted connector op (read/validate/apply/lifecycle)
}

type ServerMessage_TerminalInput struct {
	TerminalInput *TerminalInput `protobuf:"bytes,6,opt,name=terminal_input,json=terminalInput,proto3,oneof"` // web terminal: open / stdin / resize / close
}

func (*ServerMessage_SyncJobs) isServerMessage_Body() {}

func (*ServerMessage_RunNow) isServerMessage_Body() {}

func (*ServerMessage_CancelRun) isServerMessage_Body() {}

func (*ServerMessage_UpdateAgent) isServerMessage_Body() {}

func (*ServerMessage_ConnectorCommand) isServerMessage_Body() {}

func (*ServerMessage_TerminalInput) isServerMessage_Body() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	SyncCursor    string                 `protobuf:"bytes,4,opt,name=sync_cursor,json=syncCursor,proto3" json:"sync_cursor,omitempty"` // last applied SyncJobs cursor, may be empty on first connect
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Hello) GetSyncCursor() string {
	if x != nil {
		return x.SyncCursor
	}
	return ""
}

func (x *Hello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	RunningRunIds []string               `protobuf:"bytes,2,rep,name=running_run_ids,json=runningRunIds,proto3" json:"running_run_ids,omitempty"`
	LoadAvg_1M    float64                `protobuf:"fixed64,3,opt,name=load_avg_1m,json=loadAvg1m,proto3" json:"load_avg_1m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Heartbeat) GetRunningRunIds() []string {
	if x != nil {
		return x.RunningRunIds
	}
	return nil
}

func (x *Heartbeat) GetLoadAvg_1M() float64 {
	if x != nil {
		return x.LoadAvg_1M
	}
	return 0
}

type ConfigAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppliedCursor string                 `protobuf:"bytes,1,opt,name=applied_cursor,json=appliedCursor,proto3" json:"applied_cursor,omitempty"`
	JobVersionIds []string               `protobuf:"bytes,2,rep,name=job_version_ids,json=jobVersionIds,proto3" json:"job_version_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAck) Reset() {
	*x = ConfigAck{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAck) ProtoMessage() {}

func (x *ConfigAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAck.ProtoReflect.Descriptor instead.
func (*ConfigAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigAck) GetAppliedCursor() string {
	if x != nil {
		return x.AppliedCursor
	}
	return ""
}

func (x *ConfigAck) GetJobVersionIds() []string {
	if x != nil {
		return x.JobVersionIds
	}
	return nil
}

type RunStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobVersionId  string                 `protobuf:"bytes,3,opt,name=job_version_id,json=jobVersionId,proto3" json:"job_version_id,omitempty"`
	Trigger       string                 `protobuf:"bytes,4,opt,name=trigger,proto3" json:"trigger,omitempty"` // schedule | manual | api
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStarted) Reset() {
	*x = RunStarted{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStarted) ProtoMessage() {}

func (x *RunStarted) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStarted.ProtoReflect.Descriptor instead.
func (*RunStarted) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *RunStarted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunStarted) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunStarted) GetJobVersionId() string {
	if x != nil {
		return x.JobVersionId
	}
	return ""
}

func (x *RunStarted) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *RunStarted) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"` // stdout | stderr
	Seq           int32                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *LogChunk) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *LogChunk) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogChunk) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RunFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // succeeded | failed | timed_out | canceled
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	DurationMs    int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFinished) Reset() {
	*x = RunFinished{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFinished) ProtoMessage() {}

func (x *RunFinished) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFinished.ProtoReflect.Descriptor instead.
func (*RunFinished) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RunFinished) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunFinished) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunFinished) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunFinished) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *RunFinished) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RunFinished) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JobDef struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VersionId         string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	VersionNumber     int32                  `protobuf:"varint,3,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Interpreter       string                 `protobuf:"bytes,5,opt,name=interpreter,proto3" json:"interpreter,omitempty"`
	ScriptBody        string                 `protobuf:"bytes,6,opt,name=script_body,json=scriptBody,proto3" json:"script_body,omitempty"`
	ScheduleCron      string                 `protobuf:"bytes,7,opt,name=schedule_cron,json=scheduleCron,proto3" json:"schedule_cron,omitempty"`
	Timezone          string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Enabled           bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TimeoutSeconds    int32                  `protobuf:"varint,10,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ConcurrencyPolicy string                 `protobuf:"bytes,11,opt,name=concurrency_policy,json=concurrencyPolicy,proto3" json:"concurrency_policy,omitempty"`
	CatchupPolicy     string                 `protobuf:"bytes,12,opt,name=catchup_policy,json=catchupPolicy,proto3" json:"catchup_policy,omitempty"`
	MaxRetries        int32                  `protobuf:"varint,13,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	WorkingDir        string                 `protobuf:"bytes,14,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	RunAsUser         string                 `protobuf:"bytes,15,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	Env               map[string]string      `protobuf:"bytes,16,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`         // non-secret env
	Secrets           map[string]string      `protobuf:"bytes,17,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // resolved secret values, by env var name
	// Resource limits, enforced by the agent via systemd-run when available.
	// 0 means unlimited.
	CpuQuotaPercent int32 `protobuf:"varint,18,opt,name=cpu_quota_percent,json=cpuQuotaPercent,proto3" json:"cpu_quota_percent,omitempty"` // 100 = one full core, 200 = two cores, etc.
	MemoryMaxMb     int32 `protobuf:"varint,19,opt,name=memory_max_mb,json=memoryMaxMb,proto3" json:"memory_max_mb,omitempty"`
	TasksMax        int32 `protobuf:"varint,20,opt,name=tasks_max,json=tasksMax,proto3" json:"tasks_max,omitempty"` // cap on processes/threads; what stops a fork bomb
	IoWeight        int32 `protobuf:"varint,21,opt,name=io_weight,json=ioWeight,proto3" json:"io_weight,omitempty"` // 1..10000 relative block IO priority; 0 = default
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobDef) Reset() {
	*x = JobDef{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDef) ProtoMessage() {}

func (x *JobDef) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDef.ProtoReflect.Descriptor instead.
func (*JobDef) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *JobDef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobDef) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *JobDef) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *JobDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobDef) GetInterpreter() string {
	if x != nil {
		return x.Interpreter
	}
	return ""
}

func (x *JobDef) GetScriptBody() string {
	if x != nil {
		return x.ScriptBody
	}
	return ""
}

func (x *JobDef) GetScheduleCron() string {
	if x != nil {
		return x.ScheduleCron
	}
	return ""
}

func (x *JobDef) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *JobDef) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *JobDef) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *JobDef) GetConcurrencyPolicy() string {
	if x != nil {
		return x.ConcurrencyPolicy
	}
	return ""
}

func (x *JobDef) GetCatchupPolicy() string {
	if x != nil {
		return x.CatchupPolicy
	}
	return ""
}

func (x *JobDef) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *JobDef) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *JobDef) GetRunAsUser() string {
	if x != nil {
		return x.RunAsUser
	}
	return ""
}

func (x *JobDef) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *JobDef) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *JobDef) GetCpuQuotaPercent() int32 {
	if x != nil {
		return x.CpuQuotaPercent
	}
	return 0
}

func (x *JobDef) GetMemoryMaxMb() int32 {
	if x != nil {
		return x.MemoryMaxMb
	}
	return 0
}

func (x *JobDef) GetTasksMax() int32 {
	if x != nil {
		return x.TasksMax
	}
	return 0
}

func (x *JobDef) GetIoWeight() int32 {
	if x != nil {
		return x.IoWeight
	}
	return 0
}

type SyncJobs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"` // monotonically increasing config version
	Upsert        []*JobDef              `protobuf:"bytes,2,rep,name=upsert,proto3" json:"upsert,omitempty"`
	Delete        []string               `protobuf:"bytes,3,rep,name=delete,proto3" json:"delete,omitempty"`                                  // job ids to remove
	FullSnapshot  bool                   `protobuf:"varint,4,opt,name=full_snapshot,json=fullSnapshot,proto3" json:"full_snapshot,omitempty"` // true when this is the full set, not a delta
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncJobs) Reset() {
	*x = SyncJobs{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncJobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncJobs) ProtoMessage() {}

func (x *SyncJobs) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncJobs.ProtoReflect.Descriptor instead.
func (*SyncJobs) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *SyncJobs) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SyncJobs) GetUpsert() []*JobDef {
	if x != nil {
		return x.Upsert
	}
	return nil
}

func (x *SyncJobs) GetDelete() []string {
	if x != nil {
		return x.Delete
	}
	return nil
}

func (x *SyncJobs) GetFullSnapshot() bool {
	if x != nil {
		return x.FullSnapshot
	}
	return false
}

type RunNow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobVersionId  string                 `protobuf:"bytes,2,opt,name=job_version_id,json=jobVersionId,proto3" json:"job_version_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // server-assigned for manual triggers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunNow) Reset() {
	*x = RunNow{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunNow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunNow) ProtoMessage() {}

func (x *RunNow) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunNow.ProtoReflect.Descriptor instead.
func (*RunNow) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *RunNow) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunNow) GetJobVersionId() string {
	if x != nil {
		return x.JobVersionId
	}
	return ""
}

func (x *RunNow) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CancelRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRun) Reset() {
	*x = CancelRun{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRun) ProtoMessage() {}

func (x *CancelRun) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRun.ProtoReflect.Descriptor instead.
func (*CancelRun) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *CancelRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type UpdateAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetVersion string                 `protobuf:"bytes,1,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`    // hex digest of the binary at download_url; required
	Restart       bool                   `protobuf:"varint,4,opt,name=restart,proto3" json:"restart,omitempty"` // exit after swapping so the supervisor restarts us
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgent) Reset() {
	*x = UpdateAgent{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgent) ProtoMessage() {}

func (x *UpdateAgent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgent.ProtoReflect.Descriptor instead.
func (*UpdateAgent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateAgent) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *UpdateAgent) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UpdateAgent) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UpdateAgent) GetRestart() bool {
	if x != nil {
		return x.Restart
	}
	return false
}

type DiscoveredConnector struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Kind        string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`         // nginx|apache|caddy|traefik|haproxy|pm2|systemd|docker|cron|ufw
	Instance    string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"` // e.g. pm2 user; empty for singletons
	Version     string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status      string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`          // running|stopped|degraded|unknown
	Manageable  bool                   `protobuf:"varint,5,opt,name=manageable,proto3" json:"manageable,omitempty"` // agent has privilege to act, not just read
	ConfigPaths []string               `protobuf:"bytes,6,rep,name=config_paths,json=configPaths,proto3" json:"config_paths,omitempty"`
	ObjectCount int32                  `protobuf:"varint,7,opt,name=object_count,json=objectCount,proto3" json:"object_count,omitempty"`
	// Capabilities the agent can actually perform on this host.
	ManagesConfig  bool                 `protobuf:"varint,8,opt,name=manages_config,json=managesConfig,proto3" json:"manages_config,omitempty"`
	ManagesObjects bool                 `protobuf:"varint,9,opt,name=manages_objects,json=managesObjects,proto3" json:"manages_objects,omitempty"`
	CanValidate    bool                 `protobuf:"varint,10,opt,name=can_validate,json=canValidate,proto3" json:"can_validate,omitempty"`
	CanReload      bool                 `protobuf:"varint,11,opt,name=can_reload,json=canReload,proto3" json:"can_reload,omitempty"`
	CanLifecycle   bool                 `protobuf:"varint,12,opt,name=can_lifecycle,json=canLifecycle,proto3" json:"can_lifecycle,omitempty"`
	CanEdit        bool                 `protobuf:"varint,13,opt,name=can_edit,json=canEdit,proto3" json:"can_edit,omitempty"`
	Detail         map[string]string    `protobuf:"bytes,14,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources      []*ConnectorResource `protobuf:"bytes,15,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiscoveredConnector) Reset() {
	*x = DiscoveredConnector{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredConnector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredConnector) ProtoMessage() {}

func (x *DiscoveredConnector) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredConnector.ProtoReflect.Descriptor instead.
func (*DiscoveredConnector) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *DiscoveredConnector) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DiscoveredConnector) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *DiscoveredConnector) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DiscoveredConnector) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DiscoveredConnector) GetManageable() bool {
	if x != nil {
		return x.Manageable
	}
	return false
}

func (x *DiscoveredConnector) GetConfigPaths() []string {
	if x != nil {
		return x.ConfigPaths
	}
	return nil
}

func (x *DiscoveredConnector) GetObjectCount() int32 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

func (x *DiscoveredConnector) GetManagesConfig() bool {
	if x != nil {
		return x.ManagesConfig
	}
	return false
}

func (x *DiscoveredConnector) GetManagesObjects() bool {
	if x != nil {
		return x.ManagesObjects
	}
	return false
}

func (x *DiscoveredConnector) GetCanValidate() bool {
	if x != nil {
		return x.CanValidate
	}
	return false
}

func (x *DiscoveredConnector) GetCanReload() bool {
	if x != nil {
		return x.CanReload
	}
	return false
}

func (x *DiscoveredConnector) GetCanLifecycle() bool {
	if x != nil {
		return x.CanLifecycle
	}
	return false
}

func (x *DiscoveredConnector) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *DiscoveredConnector) GetDetail() map[string]string {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *DiscoveredConnector) GetResources() []*ConnectorResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ConnectorResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // config_file|object
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`   // path | unit | container id | pm2 id | rule number
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"` // objects: active|running|stopped|enabled; empty for files
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorResource) Reset() {
	*x = ConnectorResource{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorResource) ProtoMessage() {}

func (x *ConnectorResource) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorResource.ProtoReflect.Descriptor instead.
func (*ConnectorResource) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ConnectorResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConnectorResource) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ConnectorResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectorResource) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ConnectorResource) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ConnectorResource) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ConnectorResource) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ConnectorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Connectors    []*DiscoveredConnector `protobuf:"bytes,2,rep,name=connectors,proto3" json:"connectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorEvent) Reset() {
	*x = ConnectorEvent{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorEvent) ProtoMessage() {}

func (x *ConnectorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorEvent.ProtoReflect.Descriptor instead.
func (*ConnectorEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ConnectorEvent) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *ConnectorEvent) GetConnectors() []*DiscoveredConnector {
	if x != nil {
		return x.Connectors
	}
	return nil
}

type ConnectorCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // ULID, correlates the reply
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`                                // discover|status|list|read|validate|apply|lifecycle|rollback
	ConnectorKind string                 `protobuf:"bytes,3,opt,name=connector_kind,json=connectorKind,proto3" json:"connector_kind,omitempty"`
	ConnectorId   string                 `protobuf:"bytes,4,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	Ref           string                 `protobuf:"bytes,5,opt,name=ref,proto3" json:"ref,omitempty"`                                       // path | unit | container | pm2 id | rule number
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`                                 // lifecycle: start|stop|restart|reload|enable|disable
	Content       []byte                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`                               // apply: proposed config bytes
	BaseChecksum  string                 `protobuf:"bytes,8,opt,name=base_checksum,json=baseChecksum,proto3" json:"base_checksum,omitempty"` // optimistic concurrency
	DryRun        bool                   `protobuf:"varint,9,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorCommand) Reset() {
	*x = ConnectorCommand{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorCommand) ProtoMessage() {}

func (x *ConnectorCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorCommand.ProtoReflect.Descriptor instead.
func (*ConnectorCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ConnectorCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectorCommand) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ConnectorCommand) GetConnectorKind() string {
	if x != nil {
		return x.ConnectorKind
	}
	return ""
}

func (x *ConnectorCommand) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *ConnectorCommand) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ConnectorCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ConnectorCommand) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ConnectorCommand) GetBaseChecksum() string {
	if x != nil {
		return x.BaseChecksum
	}
	return ""
}

func (x *ConnectorCommand) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type ConnectorStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorStep) Reset() {
	*x = ConnectorStep{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorStep) ProtoMessage() {}

func (x *ConnectorStep) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorStep.ProtoReflect.Descriptor instead.
func (*ConnectorStep) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ConnectorStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectorStep) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ConnectorStep) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ConnectorStep) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ConnectorResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // succeeded|failed|invalid|unauthorized|unsupported
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // validator output / human-readable detail
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // read: config bytes
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Steps         []*ConnectorStep       `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,7,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorResult) Reset() {
	*x = ConnectorResult{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorResult) ProtoMessage() {}

func (x *ConnectorResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorResult.ProtoReflect.Descriptor instead.
func (*ConnectorResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ConnectorResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectorResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConnectorResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectorResult) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ConnectorResult) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ConnectorResult) GetSteps() []*ConnectorStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ConnectorResult) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`                    // open | data | resize | close | signal
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`                // open: shell (interactive pty) | command (one-shot)
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                // data: stdin bytes
	Cols          uint32                 `protobuf:"varint,5,opt,name=cols,proto3" json:"cols,omitempty"`               // open/resize: terminal width
	Rows          uint32                 `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`               // open/resize: terminal height
	Command       string                 `protobuf:"bytes,7,opt,name=command,proto3" json:"command,omitempty"`          // open+command: the one-shot command line to run
	Signal        string                 `protobuf:"bytes,8,opt,name=signal,proto3" json:"signal,omitempty"`            // signal: INT | TERM | QUIT | KILL
	RunAs         string                 `protobuf:"bytes,9,opt,name=run_as,json=runAs,proto3" json:"run_as,omitempty"` // open: OS user to run as; empty = the agent's own user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *TerminalInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalInput) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *TerminalInput) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TerminalInput) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalInput) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalInput) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TerminalInput) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *TerminalInput) GetRunAs() string {
	if x != nil {
		return x.RunAs
	}
	return ""
}

type TerminalOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                          // data | started | exit | error
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                          // data: pty output bytes
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // exit: process exit code
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                    // error / exit: human-readable detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOutput) Reset() {
	*x = TerminalOutput{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOutput) ProtoMessage() {}

func (x *TerminalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOutput.ProtoReflect.Descriptor instead.
func (*TerminalOutput) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *TerminalOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOutput) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TerminalOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TerminalOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TerminalOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x14croncompose.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x17\n" +
	"\acsr_pem\x18\x05 \x01(\fR\x06csrPem\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\"\xd1\x01\n" +
	"\x0eEnrollResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12&\n" +
	"\x0fclient_cert_pem\x18\x02 \x01(\fR\rclientCertPem\x12\"\n" +
	"\rserver_ca_pem\x18\x03 \x01(\fR\vserverCaPem\x125\n" +
	"\x17control_plane_grpc_addr\x18\x04 \x01(\tR\x14controlPlaneGrpcAddr\x12\x1f\n" +
	"\vagent_token\x18\x05 \x01(\tR\n" +
	"agentToken\"\x90\x05\n" +
	"\fAgentMessage\x123\n" +
	"\x05hello\x18\x01 \x01(\v2\x1b.croncompose.agent.v1.HelloH\x00R\x05hello\x12?\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1f.croncompose.agent.v1.HeartbeatH\x00R\theartbeat\x12@\n" +
	"\n" +
	"config_ack\x18\x03 \x01(\v2\x1f.croncompose.agent.v1.ConfigAckH\x00R\tconfigAck\x12C\n" +
	"\vrun_started\x18\x04 \x01(\v2 .croncompose.agent.v1.RunStartedH\x00R\n" +
	"runStarted\x12=\n" +
	"\tlog_chunk\x18\x05 \x01(\v2\x1e.croncompose.agent.v1.LogChunkH\x00R\blogChunk\x12F\n" +
	"\frun_finished\x18\x06 \x01(\v2!.croncompose.agent.v1.RunFinishedH\x00R\vrunFinished\x12O\n" +
	"\x0fconnector_event\x18\a \x01(\v2$.croncompose.agent.v1.ConnectorEventH\x00R\x0econnectorEvent\x12R\n" +
	"\x10connector_result\x18\b \x01(\v2%.croncompose.agent.v1.ConnectorResultH\x00R\x0fconnectorResult\x12O\n" +
	"\x0fterminal_output\x18\t \x01(\v2$.croncompose.agent.v1.TerminalOutputH\x00R\x0eterminalOutputB\x06\n" +
	"\x04body\"\xbe\x03\n" +
	"\rServerMessage\x12=\n" +
	"\tsync_jobs\x18\x01 \x01(\v2\x1e.croncompose.agent.v1.SyncJobsH\x00R\bsyncJobs\x127\n" +
	"\arun_now\x18\x02 \x01(\v2\x1c.croncompose.agent.v1.RunNowH\x00R\x06runNow\x12@\n" +
	"\n" +
	"cancel_run\x18\x03 \x01(\v2\x1f.croncompose.agent.v1.CancelRunH\x00R\tcancelRun\x12F\n" +
	"\fupdate_agent\x18\x04 \x01(\v2!.croncompose.agent.v1.UpdateAgentH\x00R\vupdateAgent\x12U\n" +
	"\x11connector_command\x18\x05 \x01(\v2&.croncompose.agent.v1.ConnectorCommandH\x00R\x10connectorCommand\x12L\n" +
	"\x0eterminal_input\x18\x06 \x01(\v2#.croncompose.agent.v1.TerminalInputH\x00R\rterminalInputB\x06\n" +
	"\x04body\"\x95\x01\n" +
	"\x05Hello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1f\n" +
	"\vsync_cursor\x18\x04 \x01(\tR\n" +
	"syncCursor\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"\x7f\n" +
	"\tHeartbeat\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12&\n" +
	"\x0frunning_run_ids\x18\x02 \x03(\tR\rrunningRunIds\x12\x1e\n" +
	"\vload_avg_1m\x18\x03 \x01(\x01R\tloadAvg1m\"Z\n" +
	"\tConfigAck\x12%\n" +
	"\x0eapplied_cursor\x18\x01 \x01(\tR\rappliedCursor\x12&\n" +
	"\x0fjob_version_ids\x18\x02 \x03(\tR\rjobVersionIds\"\xb5\x01\n" +
	"\n" +
	"RunStarted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12$\n" +
	"\x0ejob_version_id\x18\x03 \x01(\tR\fjobVersionId\x12\x18\n" +
	"\atrigger\x18\x04 \x01(\tR\atrigger\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"_\n" +
	"\bLogChunk\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x05R\x03seq\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xcd\x01\n" +
	"\vRunFinished\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12;\n" +
	"\vfinished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xed\x06\n" +
	"\x06JobDef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x12%\n" +
	"\x0eversion_number\x18\x03 \x01(\x05R\rversionNumber\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vinterpreter\x18\x05 \x01(\tR\vinterpreter\x12\x1f\n" +
	"\vscript_body\x18\x06 \x01(\tR\n" +
	"scriptBody\x12#\n" +
	"\rschedule_cron\x18\a \x01(\tR\fscheduleCron\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x12'\n" +
	"\x0ftimeout_seconds\x18\n" +
	" \x01(\x05R\x0etimeoutSeconds\x12-\n" +
	"\x12concurrency_policy\x18\v \x01(\tR\x11concurrencyPolicy\x12%\n" +
	"\x0ecatchup_policy\x18\f \x01(\tR\rcatchupPolicy\x12\x1f\n" +
	"\vmax_retries\x18\r \x01(\x05R\n" +
	"maxRetries\x12\x1f\n" +
	"\vworking_dir\x18\x0e \x01(\tR\n" +
	"workingDir\x12\x1e\n" +
	"\vrun_as_user\x18\x0f \x01(\tR\trunAsUser\x127\n" +
	"\x03env\x18\x10 \x03(\v2%.croncompose.agent.v1.JobDef.EnvEntryR\x03env\x12C\n" +
	"\asecrets\x18\x11 \x03(\v2).croncompose.agent.v1.JobDef.SecretsEntryR\asecrets\x12*\n" +
	"\x11cpu_quota_percent\x18\x12 \x01(\x05R\x0fcpuQuotaPercent\x12\"\n" +
	"\rmemory_max_mb\x18\x13 \x01(\x05R\vmemoryMaxMb\x12\x1b\n" +
	"\ttasks_max\x18\x14 \x01(\x05R\btasksMax\x12\x1b\n" +
	"\tio_weight\x18\x15 \x01(\x05R\bioWeight\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x01\n" +
	"\bSyncJobs\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x124\n" +
	"\x06upsert\x18\x02 \x03(\v2\x1c.croncompose.agent.v1.JobDefR\x06upsert\x12\x16\n" +
	"\x06delete\x18\x03 \x03(\tR\x06delete\x12#\n" +
	"\rfull_snapshot\x18\x04 \x01(\bR\ffullSnapshot\"\\\n" +
	"\x06RunNow\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12$\n" +
	"\x0ejob_version_id\x18\x02 \x01(\tR\fjobVersionId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"\"\n" +
	"\tCancelRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x89\x01\n" +
	"\vUpdateAgent\x12%\n" +
	"\x0etarget_version\x18\x01 \x01(\tR\rtargetVersion\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x18\n" +
	"\arestart\x18\x04 \x01(\bR\arestart\"\x80\x05\n" +
	"\x13DiscoveredConnector\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"manageable\x18\x05 \x01(\bR\n" +
	"manageable\x12!\n" +
	"\fconfig_paths\x18\x06 \x03(\tR\vconfigPaths\x12!\n" +
	"\fobject_count\x18\a \x01(\x05R\vobjectCount\x12%\n" +
	"\x0emanages_config\x18\b \x01(\bR\rmanagesConfig\x12'\n" +
	"\x0fmanages_objects\x18\t \x01(\bR\x0emanagesObjects\x12!\n" +
	"\fcan_validate\x18\n" +
	" \x01(\bR\vcanValidate\x12\x1d\n" +
	"\n" +
	"can_reload\x18\v \x01(\bR\tcanReload\x12#\n" +
	"\rcan_lifecycle\x18\f \x01(\bR\fcanLifecycle\x12\x19\n" +
	"\bcan_edit\x18\r \x01(\bR\acanEdit\x12M\n" +
	"\x06detail\x18\x0e \x03(\v25.croncompose.agent.v1.DiscoveredConnector.DetailEntryR\x06detail\x12E\n" +
	"\tresources\x18\x0f \x03(\v2'.croncompose.agent.v1.ConnectorResourceR\tresources\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x02\n" +
	"\x11ConnectorResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12W\n" +
	"\n" +
	"attributes\x18\a \x03(\v27.croncompose.agent.v1.ConnectorResource.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x0eConnectorEvent\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12I\n" +
	"\n" +
	"connectors\x18\x02 \x03(\v2).croncompose.agent.v1.DiscoveredConnectorR\n" +
	"connectors\"\x8d\x02\n" +
	"\x10ConnectorCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12%\n" +
	"\x0econnector_kind\x18\x03 \x01(\tR\rconnectorKind\x12!\n" +
	"\fconnector_id\x18\x04 \x01(\tR\vconnectorId\x12\x10\n" +
	"\x03ref\x18\x05 \x01(\tR\x03ref\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x18\n" +
	"\acontent\x18\a \x01(\fR\acontent\x12#\n" +
	"\rbase_checksum\x18\b \x01(\tR\fbaseChecksum\x12\x17\n" +
	"\adry_run\x18\t \x01(\bR\x06dryRun\"h\n" +
	"\rConnectorStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\"\xf6\x01\n" +
	"\x0fConnectorResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x129\n" +
	"\x05steps\x18\x06 \x03(\v2#.croncompose.agent.v1.ConnectorStepR\x05steps\x12!\n" +
	"\fpayload_json\x18\a \x01(\fR\vpayloadJson\"\xd7\x01\n" +
	"\rTerminalInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x12\n" +
	"\x04cols\x18\x05 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\rR\x04rows\x12\x18\n" +
	"\acommand\x18\a \x01(\tR\acommand\x12\x16\n" +
	"\x06signal\x18\b \x01(\tR\x06signal\x12\x15\n" +
	"\x06run_as\x18\t \x01(\tR\x05runAs\"\x8e\x01\n" +
	"\x0eTerminalOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage2\xbf\x01\n" +
	"\fAgentService\x12S\n" +
	"\x06Enroll\x12#.croncompose.agent.v1.EnrollRequest\x1a$.croncompose.agent.v1.EnrollResponse\x12Z\n" +
	"\vAgentStream\x12\".croncompose.agent.v1.AgentMessage\x1a#.croncompose.agent.v1.ServerMessage(\x010\x01B;Z9github.com/croncompose/croncompose/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_agent_proto_goTypes = []any{
	(*EnrollRequest)(nil),         // 0: croncompose.agent.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 1: croncompose.agent.v1.EnrollResponse
	(*AgentMessage)(nil),          // 2: croncompose.agent.v1.AgentMessage
	(*ServerMessage)(nil),         // 3: croncompose.agent.v1.ServerMessage
	(*Hello)(nil),                 // 4: croncompose.agent.v1.Hello
	(*Heartbeat)(nil),             // 5: croncompose.agent.v1.Heartbeat
	(*ConfigAck)(nil),             // 6: croncompose.agent.v1.ConfigAck
	(*RunStarted)(nil),            // 7: croncompose.agent.v1.RunStarted
	(*LogChunk)(nil),              // 8: croncompose.agent.v1.LogChunk
	(*RunFinished)(nil),           // 9: croncompose.agent.v1.RunFinished
	(*JobDef)(nil),                // 10: croncompose.agent.v1.JobDef
	(*SyncJobs)(nil),              // 11: croncompose.agent.v1.SyncJobs
	(*RunNow)(nil),                // 12: croncompose.agent.v1.RunNow
	(*CancelRun)(nil),             // 13: croncompose.agent.v1.CancelRun
	(*UpdateAgent)(nil),           // 14: croncompose.agent.v1.UpdateAgent
	(*DiscoveredConnector)(nil),   // 15: croncompose.agent.v1.DiscoveredConnector
	(*ConnectorResource)(nil),     // 16: croncompose.agent.v1.ConnectorResource
	(*ConnectorEvent)(nil),        // 17: croncompose.agent.v1.ConnectorEvent
	(*ConnectorCommand)(nil),      // 18: croncompose.agent.v1.ConnectorCommand
	(*ConnectorStep)(nil),         // 19: croncompose.agent.v1.ConnectorStep
	(*ConnectorResult)(nil),       // 20: croncompose.agent.v1.ConnectorResult
	(*TerminalInput)(nil),         // 21: croncompose.agent.v1.TerminalInput
	(*TerminalOutput)(nil),        // 22: croncompose.agent.v1.TerminalOutput
	nil,                           // 23: croncompose.agent.v1.JobDef.EnvEntry
	nil,                           // 24: croncompose.agent.v1.JobDef.SecretsEntry
	nil,                           // 25: croncompose.agent.v1.DiscoveredConnector.DetailEntry
	nil,                           // 26: croncompose.agent.v1.ConnectorResource.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 27: google.protobuf.Timestamp
}
var file_agent_proto_depIdxs = []int32{
	4,  // 0: croncompose.agent.v1.AgentMessage.hello:type_name -> croncompose.agent.v1.Hello
	5,  // 1: croncompose.agent.v1.AgentMessage.heartbeat:type_name -> croncompose.agent.v1.Heartbeat
	6,  // 2: croncompose.agent.v1.AgentMessage.config_ack:type_name -> croncompose.agent.v1.ConfigAck
	7,  // 3: croncompose.agent.v1.AgentMessage.run_started:type_name -> croncompose.agent.v1.RunStarted
	8,  // 4: croncompose.agent.v1.AgentMessage.log_chunk:type_name -> croncompose.agent.v1.LogChunk
	9,  // 5: croncompose.agent.v1.AgentMessage.run_finished:type_name -> croncompose.agent.v1.RunFinished
	17, // 6: croncompose.agent.v1.AgentMessage.connector_event:type_name -> croncompose.agent.v1.ConnectorEvent
	20, // 7: croncompose.agent.v1.AgentMessage.connector_result:type_name -> croncompose.agent.v1.ConnectorResult
	22, // 8: croncompose.agent.v1.AgentMessage.terminal_output:type_name -> croncompose.agent.v1.TerminalOutput
	11, // 9: croncompose.agent.v1.ServerMessage.sync_jobs:type_name -> croncompose.agent.v1.SyncJobs
	12, // 10: croncompose.agent.v1.ServerMessage.run_now:type_name -> croncompose.agent.v1.RunNow
	13, // 11: croncompose.agent.v1.ServerMessage.cancel_run:type_name -> croncompose.agent.v1.CancelRun
	14, // 12: croncompose.agent.v1.ServerMessage.update_agent:type_name -> croncompose.agent.v1.UpdateAgent
	18, // 13: croncompose.agent.v1.ServerMessage.connector_command:type_name -> croncompose.agent.v1.ConnectorCommand
	21, // 14: croncompose.agent.v1.ServerMessage.terminal_input:type_name -> croncompose.agent.v1.TerminalInput
	27, // 15: croncompose.agent.v1.Heartbeat.ts:type_name -> google.protobuf.Timestamp
	27, // 16: croncompose.agent.v1.RunStarted.started_at:type_name -> google.protobuf.Timestamp
	27, // 17: croncompose.agent.v1.RunFinished.finished_at:type_name -> google.protobuf.Timestamp
	23, // 18: croncompose.agent.v1.JobDef.env:type_name -> croncompose.agent.v1.JobDef.EnvEntry
	24, // 19: croncompose.agent.v1.JobDef.secrets:type_name -> croncompose.agent.v1.JobDef.SecretsEntry
	10, // 20: croncompose.agent.v1.SyncJobs.upsert:type_name -> croncompose.agent.v1.JobDef
	25, // 21: croncompose.agent.v1.DiscoveredConnector.detail:type_name -> croncompose.agent.v1.DiscoveredConnector.DetailEntry
	16, // 22: croncompose.agent.v1.DiscoveredConnector.resources:type_name -> croncompose.agent.v1.ConnectorResource
	26, // 23: croncompose.agent.v1.ConnectorResource.attributes:type_name -> croncompose.agent.v1.ConnectorResource.AttributesEntry
	27, // 24: croncompose.agent.v1.ConnectorEvent.ts:type_name -> google.protobuf.Timestamp
	15, // 25: croncompose.agent.v1.ConnectorEvent.connectors:type_name -> croncompose.agent.v1.DiscoveredConnector
	19, // 26: croncompose.agent.v1.ConnectorResult.steps:type_name -> croncompose.agent.v1.ConnectorStep
	0,  // 27: croncompose.agent.v1.AgentService.Enroll:input_type -> croncompose.agent.v1.EnrollRequest
	2,  // 28: croncompose.agent.v1.AgentService.AgentStream:input_type -> croncompose.agent.v1.AgentMessage
	1,  // 29: croncompose.agent.v1.AgentService.Enroll:output_type -> croncompose.agent.v1.EnrollResponse
	3,  // 30: croncompose.agent.v1.AgentService.AgentStream:output_type -> croncompose.agent.v1.ServerMessage
	29, // [29:31] is the sub-list for method output_type
	27, // [27:29] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ConfigAck)(nil),
		(*AgentMessage_RunStarted)(nil),
		(*AgentMessage_LogChunk)(nil),
		(*AgentMessage_RunFinished)(nil),
		(*AgentMessage_ConnectorEvent)(nil),
		(*AgentMessage_ConnectorResult)(nil),
		(*AgentMessage_TerminalOutput)(nil),
	}
	file_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerMessage_SyncJobs)(nil),
		(*ServerMessage_RunNow)(nil),
		(*ServerMessage_CancelRun)(nil),
		(*ServerMessage_UpdateAgent)(nil),
		(*ServerMessage_ConnectorCommand)(nil),
		(*ServerMessage_TerminalInput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
